### PR TITLE
Build stopped working, causes are quiche (set to specific version) and the nginx upgrade (I will try to look how to make it work with 1.19.7)

### PR DESCRIPTION
**Pull request by cocorossello**

### CODE REVIEW

**Comment by cocorossello** [comment]
The error is: 

```
src/http/ngx_http_request.c: In function 'ngx_http_init_connection':
src/http/ngx_http_request.c:364:40: error: 'ngx_listening_t' {aka 'struct ngx_listening_s'} has no member named 'post_accept_timeout'
  364 |         ngx_add_timer(rev, c->listening->post_accept_timeout);
      |                                        ^~

```

I guess it has something to do with:
https://github.com/winshining/nginx-http-flv-module/issues/191

**Review by RanadeepPolavarapu — APPROVED** [review]
